# permissions for end users to view fuwus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fuwu-viewer-role
rules:
- apiGroups:
  - runner.basebit.me
  resources:
  - fuwus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runner.basebit.me
  resources:
  - fuwus/status
  verbs:
  - get
